sudo: required
dist: trusty
language: node_js
matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          node_js: 8
          -os: osx
          node_js: 8
install:
    - npm install

build:
    - npm test

script:
    - npm --version

