platform:
    - x64
    - x86

install:
    - npm install

environment:
  NPM_TOKEN:
    secure: xczby7HP6CaMEUh0VCk+mOHHnRuTnLnCl5C2iRGxCPiX5yXIlvnyVZktk1rhz/NY

build_script:
    - npm test

test: off

deploy_script:
  - ps: |
      if ($ENV:PLATFORM -eq "x64")
      {
        "//registry.npmjs.org/:_authToken=`$`{NPM_TOKEN`}" | Out-File (Join-Path $ENV:APPVEYOR_BUILD_FOLDER ".npmrc") -Encoding UTF8
        iex "npm pack"
        iex "npm publish"
      }
    on:
      branch: master
